{% set name = "pytest-openfiles" %}
{% set version = "0.3.2" %}
{% set git_url = "https://github.com/astropy/pytest-openfiles" %}
{% set sha256 = "e51c91889eb9e4c75f47735efc57a1435f3f1182463600ba7bce7f2556a46884" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pytest >=3.1
    - psutil
  run:
    - python
    - pytest >=3.1
    - psutil

test:
  imports:
    - pytest_openfiles

about:
  home: {{ git_url }}
  license: BSD
  summary: 'Pytest plugin for detecting inadvertent open file handles'
  description: |
    This package provides a plugin for the pytest framework that allows
    developers to detect whether any file handles or other file-like objects
    were inadvertently left open at the end of a unit test.
  doc_url: {{ git_url }}
  dev_url: {{ git_url }}

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - drdavella
    - mwcraig
